(() => {
const form=document.querySelector('#questionnaire-form'); if(!form)return;
const steps=[...form.querySelectorAll('.q-step')], progress=document.querySelector('#q-progress'), previous=document.querySelector('#q-prev'), next=document.querySelector('#q-next'), summary=document.querySelector('#q-summary'), status=document.querySelector('#q-status'); let current=0;
const value=(name)=>form.querySelector(`[name="${name}"]`)?.value?.trim()||''; const checked=(name)=>[...form.querySelectorAll(`[name="${name}"]:checked`)].map(el=>el.value); const selectedNeed=()=>value('besoinInitial');
function setStatus(message,error=false){status.textContent=message;status.hidden=!message;status.className=`q-status ${error?'q-error':''}`;}
function branchMatches(step){const b=step.dataset.branch;if(!b)return true;return b.split(',').includes(selectedNeed());}
function visibleSteps(){return steps.filter(branchMatches);}
function showStep(index){const visible=visibleSteps();current=Math.max(0,Math.min(index,visible.length-1));steps.forEach(s=>s.classList.remove('is-active'));visible[current].classList.add('is-active');progress.style.width=`${((current+1)/visible.length)*100}%`;previous.hidden=current===0;next.hidden=false;next.disabled=false;next.textContent=current===visible.length-1?'Envoyer ma demande':'Continuer';if(current===visible.length-1)buildSummary();window.scrollTo({top:0,behavior:'smooth'});}
function validateCurrent(){const step=visibleSteps()[current];setStatus('');if(step.dataset.step==='1'&&!selectedNeed()){setStatus('Choisissez simplement ce qui correspond le mieux à votre besoin.',true);return false;}if(step.dataset.step==='3'&&!value('descriptionProjet')){setStatus('Parlez-nous un peu de votre projet pour que nous puissions vous accompagner.',true);return false;}if(step.dataset.step==='13'&&!value('descriptionLibre')&&!value('descriptionProjet')){setStatus('Décrivez-nous simplement ce que vous désirez, même si votre projet est encore flou.',true);return false;}if(step.dataset.step==='14'){if(!value('prenom')){setStatus('Indiquez votre prénom.',true);return false;}if(!value('nom')){setStatus('Indiquez votre nom.',true);return false;}if(!value('email')){setStatus('Indiquez votre adresse e-mail.',true);return false;}if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value('email'))){setStatus('Vérifiez votre adresse e-mail.',true);return false;}if(!form.querySelector('#confirmation').checked){setStatus('Confirmez les informations saisies avant l’envoi.',true);return false;}}return true;}
function escapeHtml(text){return String(text).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]));}
function buildSummary(){const items=[['Votre besoin',({traiteur:'🍽️ Une prestation traiteur',chef_domicile:'👨‍🍳 Un chef à domicile',demande_particuliere:'💬 Une demande particulière',accompagnement:'❓ Je ne sais pas encore, j’aimerais être accompagné'})[selectedNeed()]||''],['Profil',({particulier:'Un particulier',professionnel:'Un professionnel',non_renseigne:'Je ne sais pas / autre'})[value('profil')]||'Non précisé'],['Votre projet',value('descriptionProjet')||value('descriptionLibre')],['Occasion',value('occasion')],['Date',value('dateEvenement')],['Nombre de personnes',value('nombrePersonnes')],['Lieu',[value('adresse'),value('codePostal'),value('ville')].filter(Boolean).join(', ')],['Préférences / contraintes',[value('preferences'),value('alimentsPrioriser'),value('alimentsEviter'),value('contraintesAlimentaires')].filter(Boolean).join('\n')],['Budget',value('budget')]];summary.innerHTML=items.filter(([,v])=>v).map(([label,v])=>`<dt>${escapeHtml(label)}</dt><dd>${escapeHtml(v)}</dd>`).join('');}
function collect(){const data={};for(const[key,raw]of new FormData(form).entries()){if(key==='website'||key==='confirmation')continue;if(data[key]===undefined)data[key]=raw;else if(Array.isArray(data[key]))data[key].push(raw);else data[key]=[data[key],raw];}return data;}
next.addEventListener('click',async()=>{if(!validateCurrent())return;const visible=visibleSteps();if(current<visible.length-1){showStep(current+1);return;}await submit();});previous.addEventListener('click',()=>showStep(current-1));
async function submit(){next.disabled=true;next.textContent='Envoi en cours…';setStatus('');try{const payload=collect();payload.type=selectedNeed();payload.besoinInitial=selectedNeed();const response=await fetch(window.DEMANDES_ENDPOINT||'https://europe-west9-carnet-du-chef.cloudfunctions.net/submitDemande',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const result=await response.json().catch(()=>({}));if(!response.ok||!result.ok)throw new Error(result.message||'La demande n’a pas pu être envoyée.');setStatus('Votre demande a bien été envoyée. Le Carnet du Chef reviendra vers vous prochainement.');next.hidden=true;previous.hidden=true;}catch(error){setStatus(error.message||'Une erreur est survenue. Merci de réessayer.',true);next.disabled=false;next.textContent='Envoyer ma demande';}}
showStep(0);
})();