import { auth, db, FIREBASE_READY } from "../js/firebase-init.js";
import { doc, getDoc, setDoc, serverTimestamp } from "https://www.gstatic.com/firebasejs/10.13.0/firebase-firestore.js";
const COMMANDES_REF=doc(db,"siteContent","commandes");
const DEFAULTS={modeManuel:"auto",limiteDejeuner:"11:30",limiteDiner:"20:00",fermetureManuelleGlobale:false,fermetureManuelleDejeuner:false,fermetureManuelleDiner:false,fermetureExceptionnelle:{active:false,motif:"",dateDebut:null,dateFin:null}};
function ensureUI(){if(document.querySelector("#commandes-config-section"))return;const settings=document.querySelector("#settings-section");if(!settings)return;const section=document.createElement("section");section.id="commandes-config-section";section.className="admin-section admin-section-inner";section.hidden=true;section.innerHTML=`<div class="admin-section-heading compact"><div><p class="admin-eyebrow">SOURCE SERVEUR</p><h3>Horaires et fermetures des commandes</h3></div></div><div class="admin-alert"><strong>Ces paramètres sont appliqués côté serveur avant tout accès au paiement.</strong><p>Une fermeture n'annule jamais les commandes déjà payées.</p></div><form id="commandes-config-form"><div class="admin-form-grid"><div class="form-field admin-field-full"><label for="commandes-mode-manuel">État des commandes</label><select id="commandes-mode-manuel"><option value="auto">Automatique — respecter les horaires</option><option value="ouvert">Ouvert manuellement</option><option value="ferme">Fermé manuellement</option></select></div><div class="form-field"><label for="commandes-limite-dejeuner">Limite déjeuner</label><input id="commandes-limite-dejeuner" type="time" required></div><div class="form-field"><label for="commandes-limite-diner">Limite dîner</label><input id="commandes-limite-diner" type="time" required></div></div><div class="admin-checkboxes"><label class="admin-checkbox"><input id="commandes-fermeture-globale" type="checkbox"> Fermeture manuelle globale</label><label class="admin-checkbox"><input id="commandes-fermeture-dejeuner" type="checkbox"> Fermeture manuelle déjeuner</label><label class="admin-checkbox"><input id="commandes-fermeture-diner" type="checkbox"> Fermeture manuelle dîner</label><label class="admin-checkbox"><input id="commandes-fermeture-exceptionnelle" type="checkbox"> Fermeture exceptionnelle active</label></div><div class="admin-form-actions"><button id="commandes-config-save" type="submit" class="btn btn-primary">Enregistrer les paramètres</button><span id="commandes-config-status" class="muted" aria-live="polite"></span></div></form>`;settings.appendChild(section);}
function e(){return{section:document.querySelector("#commandes-config-section"),form:document.querySelector("#commandes-config-form"),mode:document.querySelector("#commandes-mode-manuel"),dej:document.querySelector("#commandes-limite-dejeuner"),din:document.querySelector("#commandes-limite-diner"),glob:document.querySelector("#commandes-fermeture-globale"),dejClosed:document.querySelector("#commandes-fermeture-dejeuner"),dinClosed:document.querySelector("#commandes-fermeture-diner"),exc:document.querySelector("#commandes-fermeture-exceptionnelle"),status:document.querySelector("#commandes-config-status"),save:document.querySelector("#commandes-config-save")};}
function status(m="",err=false){const x=e().status;if(x){x.textContent=m;x.className=`muted ${err?"admin-alert admin-alert-error":""}`;}}
function apply(data={}){const x=e(),ex={...DEFAULTS.fermetureExceptionnelle,...(data.fermetureExceptionnelle||{})};x.mode.value=["auto","ouvert","ferme"].includes(data.modeManuel)?data.modeManuel:"auto";x.dej.value=data.limiteDejeuner||DEFAULTS.limiteDejeuner;x.din.value=data.limiteDiner||DEFAULTS.limiteDiner;x.glob.checked=data.fermetureManuelleGlobale===true;x.dejClosed.checked=data.fermetureManuelleDejeuner===true;x.dinClosed.checked=data.fermetureManuelleDiner===true;x.exc.checked=ex.active===true;}
async function load(){const x=e();if(!auth.currentUser||!x.form)return;try{const s=await getDoc(COMMANDES_REF);apply(s.exists()?s.data():{});}catch(err){console.error(err);status("Impossible de charger les paramètres.",true);}}
async function save(ev){ev.preventDefault();const x=e();if(!auth.currentUser)return;x.save.disabled=true;try{await setDoc(COMMANDES_REF,{modeManuel:x.mode.value,limiteDejeuner:x.dej.value,limiteDiner:x.din.value,fermetureManuelleGlobale:x.glob.checked,fermetureManuelleDejeuner:x.dejClosed.checked,fermetureManuelleDiner:x.dinClosed.checked,updatedAt:serverTimestamp()},{merge:true});status("Paramètres enregistrés.");}catch(err){console.error(err);status("Enregistrement impossible.",true);}finally{x.save.disabled=false;}}
function init(){ensureUI();const x=e();if(!x.form||!FIREBASE_READY)return;x.form.addEventListener("submit",save);auth.onAuthStateChanged(user=>{x.section.hidden=!user;if(user)void load();});}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init,{once:true});else init();
import("./finance.js");
import("./finance-enhancer.js");
