import { auth, db, FIREBASE_READY } from "../js/firebase-init.js";
import { addDoc, collection, deleteDoc, doc, getDocs, serverTimestamp, updateDoc } from "https://www.gstatic.com/firebasejs/10.13.0/firebase-firestore.js";

const STATUS = [["brouillon","Brouillon"],["envoyee","Envoyée"],["partiellement_payee","Partiellement payée"],["payee","Payée"],["annulee","Annulée"]];
let invoices = [], selectedId = null, mounted = false;
const money = (v) => `${Number(v || 0).toFixed(2).replace(".", ",")} €`;
const esc = (v) => String(v ?? "").replace(/[&<>\"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
const label = k => STATUS.find(x => x[0] === k)?.[1] || k;

function mount(){
  if(mounted) return;
  const anchor=document.querySelector("#payments-section") || document.querySelector("#quotes-section");
  if(!anchor)return;
  mounted=true;
  const s=document.createElement("section"); s.id="invoices-section"; s.className="admin-view"; s.dataset.adminView=""; s.hidden=true;
  s.innerHTML=`<div class="admin-section-heading"><div><p class="admin-eyebrow">FINANCES</p><h2>Factures</h2></div><button class="btn btn-secondary" data-i-refresh>↻ Actualiser</button></div><div class="lcc-quote-toolbar"><div class="lcc-quote-stats"><span><b data-i-count>0</b> factures</span><span><b data-i-total>0 €</b> total facturé</span><span><b data-i-paid>0 €</b> encaissé</span><span><b data-i-due>0 €</b> restant</span></div><button class="btn btn-primary" data-i-new>+ Nouvelle facture</button></div><div class="lcc-quote-layout"><div class="lcc-quote-list" data-i-list></div><aside class="lcc-quote-editor" data-i-editor><div class="lcc-demande-empty">Sélectionnez une facture ou créez-en une nouvelle.</div></aside></div>`;
  anchor.parentNode.insertBefore(s,anchor); style();
  s.querySelector("[data-i-refresh]").onclick=load; s.querySelector("[data-i-new]").onclick=()=>renderEditor(null); load();
}
async function load(){ if(!FIREBASE_READY||!auth.currentUser)return; try{const snap=await getDocs(collection(db,"factures")); invoices=snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>String(b.updatedAt||b.createdAt||"").localeCompare(String(a.updatedAt||a.createdAt||""))); renderList(); if(selectedId)renderEditor(selectedId);}catch(e){document.querySelector("[data-i-list]").innerHTML=`<div class="admin-alert admin-alert-error">Impossible de charger les factures : ${esc(e.message)}</div>`;}}
function renderList(){const list=document.querySelector("[data-i-list]"); if(!list)return; const total=invoices.reduce((s,x)=>s+Number(x.total||0),0), paid=invoices.reduce((s,x)=>s+Number(x.montantPaye||0),0); document.querySelector("[data-i-count]").textContent=invoices.length;document.querySelector("[data-i-total]").textContent=money(total);document.querySelector("[data-i-paid]").textContent=money(paid);document.querySelector("[data-i-due]").textContent=money(Math.max(0,total-paid)); if(!invoices.length){list.innerHTML='<div class="lcc-demande-empty">Aucune facture.</div>';return;} list.innerHTML=invoices.map(x=>`<button type="button" class="lcc-quote-row ${x.id===selectedId?'active':''}" data-i-id="${esc(x.id)}"><span><strong>${esc(x.numero||"Facture sans numéro")}</strong><small>${esc(x.clientNom||"Client non renseigné")}</small></span><span><b>${money(x.total)}</b><small>${label(x.statut||"brouillon")}</small></span></button>`).join("");list.querySelectorAll("[data-i-id]").forEach(b=>b.onclick=()=>{selectedId=b.dataset.iId;renderList();renderEditor(selectedId);});}
function renderEditor(id){const e=document.querySelector("[data-i-editor]");if(!e)return;const q=invoices.find(x=>x.id===id)||{statut:"brouillon",total:0,montantPaye:0};e.innerHTML=`<div class="lcc-quote-editor-head"><div><p class="admin-eyebrow">FACTURE</p><h3>${esc(q.numero||"Nouvelle facture")}</h3></div>${q.id?'<button type="button" class="btn btn-secondary" data-i-delete>Supprimer</button>':''}</div><form data-i-form><div class="admin-form-grid"><div class="form-field"><label>Numéro</label><input name="numero" value="${esc(q.numero||`FAC-${new Date().getFullYear()}-${String(Date.now()).slice(-6)}`)}" required></div><div class="form-field"><label>Statut</label><select name="statut">${STATUS.map(([k,v])=>`<option value="${k}" ${k===(q.statut||"brouillon")?'selected':''}>${v}</option>`).join("")}</select></div><div class="form-field"><label>Client</label><input name="clientNom" value="${esc(q.clientNom||"")}" required></div><div class="form-field"><label>Email</label><input name="clientEmail" type="email" value="${esc(q.clientEmail||"")}"></div><div class="form-field"><label>Date d’émission</label><input name="dateEmission" type="date" value="${esc(q.dateEmission||new Date().toISOString().slice(0,10))}"></div><div class="form-field"><label>Échéance</label><input name="dateEcheance" type="date" value="${esc(q.dateEcheance||"")}"></div><div class="form-field"><label>Total TTC</label><input name="total" type="number" min="0" step="0.01" value="${Number(q.total||0)}" required></div><div class="form-field"><label>Montant payé</label><input name="montantPaye" type="number" min="0" step="0.01" value="${Number(q.montantPaye||0)}"></div><div class="form-field admin-field-full"><label>Objet / prestation</label><input name="objet" value="${esc(q.objet||"")}"></div><div class="form-field admin-field-full"><label>Notes</label><textarea name="notes" rows="4">${esc(q.notes||"")}</textarea></div></div><div class="lcc-quote-total"><span>Reste à payer</span><strong data-i-due>${money(Math.max(0,Number(q.total||0)-Number(q.montantPaye||0)))}</strong></div><div class="admin-form-actions"><button class="btn btn-primary" type="submit">${q.id?'Enregistrer la facture':'Créer la facture'}</button>${q.clientEmail?`<a class="btn btn-secondary" href="mailto:${esc(q.clientEmail)}?subject=${encodeURIComponent(q.numero||"Votre facture — Le Carnet du Chef")}">✉ Préparer un email</a>`:""}</div></form>`;
  const f=e.querySelector("[data-i-form]"), total=f.elements.total, paid=f.elements.montantPaye; const recalc=()=>e.querySelector("[data-i-due]").textContent=money(Math.max(0,Number(total.value||0)-Number(paid.value||0))); total.oninput=recalc;paid.oninput=recalc;f.onsubmit=ev=>save(ev,q.id||null);e.querySelector("[data-i-delete]")?.addEventListener("click",()=>remove(id));recalc();}
async function save(ev,id){ev.preventDefault();const f=ev.currentTarget,d=Object.fromEntries(new FormData(f).entries());const total=Math.max(0,Number(d.total||0)),paid=Math.min(total,Math.max(0,Number(d.montantPaye||0)));let statut=d.statut;if(paid>=total&&total>0)statut="payee";else if(paid>0&&statut!=="annulee")statut="partiellement_payee";const data={numero:d.numero.trim(),statut,clientNom:d.clientNom.trim(),clientEmail:d.clientEmail.trim(),dateEmission:d.dateEmission,dateEcheance:d.dateEcheance,total,montantPaye:paid,objet:d.objet.trim(),notes:d.notes.trim(),updatedAt:serverTimestamp()};try{if(id)await updateDoc(doc(db,"factures",id),data);else{data.createdAt=serverTimestamp();const r=await addDoc(collection(db,"factures"),data);selectedId=r.id;}await load();}catch(e){alert(`Enregistrement impossible : ${e.message}`);}}
async function remove(id){if(!id||!confirm("Supprimer définitivement cette facture ?"))return;await deleteDoc(doc(db,"factures",id));selectedId=null;await load();renderEditor(null);}
function style(){if(document.querySelector("#lcc-factures-styles"))return;const st=document.createElement("style");st.id="lcc-factures-styles";st.textContent=`#invoices-section .lcc-quote-stats{display:flex;gap:1rem;flex-wrap:wrap}#invoices-section .lcc-quote-stats span{background:var(--color-white);border:1px solid var(--color-border);border-radius:var(--radius-md);padding:.65rem .8rem;font-size:.8rem}#invoices-section .lcc-quote-stats b{display:block;color:var(--color-sage-dark);font-size:1rem}`;document.head.appendChild(st);}
function init(){if(!FIREBASE_READY)return;mount();auth.onAuthStateChanged(u=>{if(u){mount();load();}});} if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
