import { auth, db } from "../js/firebase-init.js";
import { onAuthStateChanged } from "https://www.gstatic.com/firebasejs/10.13.0/firebase-auth.js";
import { collection, getDocs } from "https://www.gstatic.com/firebasejs/10.13.0/firebase-firestore.js";

/*
 * LEGACY FINANCE MODULE
 *
 * Commercial/facturation is now owned by admin/admin.js.
 * This file is intentionally kept for backward compatibility with any
 * older cached admin page that may still reference finance.js.
 *
 * IMPORTANT: this module must never render #invoices-section. The native
 * Commercial module in admin/admin.js owns that section and its complete
 * workflow (Devis -> Facture -> Stripe -> PDF -> Email).
 */

const FUNCTIONS_BASE = "https://europe-west9-carnet-du-chef.cloudfunctions.net";
let payments = [];
let refunds = [];
let started = false;

const esc = (v) => String(v ?? "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "\"": "&quot;", "'": "&#39;" }[c]));
const money = (c) => new Intl.NumberFormat("fr-FR", { style: "currency", currency: "EUR" }).format(Number(c || 0) / 100);
const millis = (v) => { if (!v) return 0; if (typeof v.toMillis === "function") return v.toMillis(); const d = new Date(v); return Number.isNaN(d.getTime()) ? 0 : d.getTime(); };
const date = (v) => { const m = millis(v); return m ? new Intl.DateTimeFormat("fr-FR", { dateStyle: "medium", timeStyle: "short" }).format(new Date(m)) : "—"; };
async function read(name) { const snap = await getDocs(collection(db, name)); return snap.docs.map((d) => ({ id: d.id, ...d.data() })); }
async function callFunction(name, body) { const user = auth.currentUser; if (!user) throw new Error("Session administrateur absente."); const token = await user.getIdToken(); const response = await fetch(`${FUNCTIONS_BASE}/${name}`, { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` }, body: JSON.stringify(body) }); const data = await response.json().catch(() => ({})); if (!response.ok || !data.ok) throw new Error(data.message || "Opération impossible."); return data; }
function style() { if (document.querySelector("#lcc-finance-style")) return; const s=document.createElement("style");s.id="lcc-finance-style";s.textContent=`.lcc-fin-grid{display:grid;grid-template-columns:minmax(0,1.5fr) minmax(280px,.8fr);gap:1rem}.lcc-fin-list{display:grid;gap:.65rem}.lcc-fin-row{display:flex;justify-content:space-between;gap:1rem;align-items:center;padding:1rem;border:1px solid var(--color-border);border-radius:var(--radius-md);background:#fff;box-shadow:var(--shadow-card)}.lcc-fin-main{min-width:0}.lcc-fin-main strong,.lcc-fin-main small{display:block}.lcc-fin-main small{margin-top:.2rem;color:var(--color-text-muted);overflow-wrap:anywhere}.lcc-fin-badge{display:inline-flex;margin-top:.4rem;padding:.25rem .55rem;border-radius:999px;background:var(--color-cream);font-size:.7rem;font-weight:800}.lcc-fin-actions{display:flex;gap:.45rem;align-items:center;flex-wrap:wrap;justify-content:flex-end}.lcc-fin-note{padding:1rem;background:var(--color-cream);border-radius:var(--radius-sm);color:var(--color-text-muted)}@media(max-width:850px){.lcc-fin-grid{grid-template-columns:1fr}.lcc-fin-row{align-items:flex-start;flex-direction:column}.lcc-fin-actions{justify-content:flex-start}}`;document.head.appendChild(s);}
function renderPayments(){const section=document.querySelector("#payments-section");if(!section)return;section.innerHTML=`<div class="admin-section-heading"><div><p class="admin-eyebrow">FINANCE</p><h2>Paiements</h2><p class="muted">Registre Stripe des paiements de commandes et de devis.</p></div><button id="lcc-pay-refresh" class="btn btn-secondary">↻ Actualiser</button></div><div class="lcc-fin-grid"><section class="admin-section"><div class="admin-section-heading compact"><h3>Paiements</h3></div><div class="lcc-fin-list">${payments.length?payments.sort((a,b)=>millis(b.createdAt)-millis(a.createdAt)).map(p=>{const refunded=refunds.filter(r=>r.paiementId===p.id).reduce((s,r)=>s+Number(r.montantCentimes||0),0);const rel=p.type==="devis"?`Devis ${p.devisId||"—"}`:`Commande ${p.commandeId||"—"}`;return `<article class="lcc-fin-row"><div class="lcc-fin-main"><strong>${esc(rel)}</strong><small>${esc(p.client?.nom||p.client?.email||"Client non renseigné")} · ${esc(date(p.paidAt||p.createdAt))}</small><small>Checkout : ${esc(p.stripeCheckoutSessionId||p.checkoutSessionId||"—")}</small><small>PaymentIntent : ${esc(p.stripePaymentIntentId||p.transactionId||"—")}</small><span class="lcc-fin-badge">${esc(p.statut||"inconnu")} · remboursé ${money(refunded)}</span></div><div class="lcc-fin-actions"><strong>${money(p.montantCentimes||p.montant)}</strong>${p.statut==="paye"?`<button class="btn btn-secondary" data-refund="${esc(p.id)}">Rembourser</button>`:""}</div></article>`}).join(""):`<div class="lcc-fin-note">Aucun paiement enregistré.</div>`}</div></section><aside class="admin-section"><h3>Remboursement</h3><div id="lcc-refund-box" class="lcc-fin-note">Sélectionnez un paiement pour ouvrir le formulaire sécurisé.</div></aside></div>`;section.querySelector("#lcc-pay-refresh")?.addEventListener("click",()=>void load());section.querySelectorAll("[data-refund]").forEach(b=>b.addEventListener("click",()=>openRefund(b.dataset.refund)));}
function openRefund(id){const p=payments.find(x=>x.id===id);const box=document.querySelector("#lcc-refund-box");if(!p||!box)return;const paid=Number(p.montantCentimes||0);const already=refunds.filter(r=>r.paiementId===id&&!['echec','annule'].includes(r.statut)).reduce((s,r)=>s+Number(r.montantCentimes||0),0);const remaining=Math.max(0,paid-already);box.innerHTML=`<p><strong>${esc(p.type==="devis"?`Devis ${p.devisId||"—"}`:`Commande ${p.commandeId||"—"}`)}</strong></p><p>Payé : ${money(paid)}<br>Déjà remboursé : ${money(already)}<br>Restant : ${money(remaining)}</p><form id="lcc-refund-form"><label>Montant (€)<input name="amount" type="number" min="0.01" max="${(remaining/100).toFixed(2)}" step="0.01" value="${(remaining/100).toFixed(2)}" required></label><label>Motif<textarea name="motif" rows="3"></textarea></label><button class="btn btn-primary" type="submit" ${remaining<=0?"disabled":""}>Rembourser via Stripe</button><div id="lcc-refund-msg" class="admin-alert" hidden></div></form>`;box.querySelector("form")?.addEventListener("submit",async(e)=>{e.preventDefault();const f=e.currentTarget;const msg=f.querySelector("#lcc-refund-msg");try{f.querySelector("button").disabled=true;const fd=new FormData(f);const result=await callFunction("refundPayment",{paiementId:id,montantCentimes:Math.round(Number(fd.get("amount"))*100),motif:String(fd.get("motif")||"").trim()});msg.textContent=`Remboursement ${result.statut} : ${money(result.montantCentimes)}.`;msg.hidden=false;await load();}catch(err){msg.textContent=err.message;msg.className="admin-alert admin-alert-error";msg.hidden=false;f.querySelector("button").disabled=false;}});}
function renderRefunds(){const section=document.querySelector("#refunds-section");if(!section)return;section.innerHTML=`<div class="admin-section-heading"><div><p class="admin-eyebrow">FINANCE</p><h2>Remboursements</h2><p class="muted">Historique des remboursements Stripe.</p></div><button id="lcc-ref-refresh" class="btn btn-secondary">↻ Actualiser</button></div><div class="lcc-fin-list">${refunds.length?refunds.sort((a,b)=>millis(b.createdAt)-millis(a.createdAt)).map(r=>`<article class="lcc-fin-row"><div class="lcc-fin-main"><strong>${esc(r.type==="devis"?`Devis ${r.devisId||"—"}`:`Commande ${r.commandeId||"—"}`)}</strong><small>Paiement : ${esc(r.paiementId||"—")} · Refund : ${esc(r.stripeRefundId||r.id)}</small><small>${esc(r.motif||"Sans motif")} · ${esc(date(r.createdAt))}</small><span class="lcc-fin-badge">${esc(r.statut||"inconnu")}</span></div><strong>${money(r.montantCentimes||r.montant)}</strong></article>`).join(""):`<div class="lcc-fin-note">Aucun remboursement enregistré.</div>`}</div>`;section.querySelector("#lcc-ref-refresh")?.addEventListener("click",()=>void load());}

/* admin/admin.js is the sole owner of #invoices-section. */
async function load(){if(!auth.currentUser)return;try{[payments,refunds]=await Promise.all([read("paiements"),read("remboursements")]);renderPayments();renderRefunds();}catch(e){console.error("Finance legacy admin",e);}}
function init(){if(started)return;started=true;style();onAuthStateChanged(auth,(u)=>{if(u)void load();});}
init();
